# Nama workflow
name: Build, Test, and Push Docker Image

# Pemicu: Berjalan setiap kali ada push ke branch 'main'
on:
  push:
    branches: [ "main" ]

# Daftar pekerjaan yang akan dijalankan
jobs:
  build_and_push:
    # Menggunakan mesin virtual Ubuntu terbaru
    runs-on: ubuntu-latest

    # Langkah-langkah kerja
    steps:
      # 1. Mengunduh kode dari repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Menyiapkan lingkungan PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      # 3. Menjalankan Unit Test
      - name: Add execute permissions to phpunit
        run: chmod +x ./vendor/bin/phpunit
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --configuration phpunit.xml

      # 4. Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Menyiapkan Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 6. Build dan Push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/uaspkpl:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/uaspkpl:${{ github.sha }}