name: Build, Test, and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Add execute permissions to phpunit
        run: chmod +x ./vendor/bin/phpunit

      - name: List files in the root directory
        run: ls -la

      - name: Sanitize phpunit.xml file
        run: sed -i '1s/^\xEF\xBB\xBF//' phpunit.xml

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --configuration phpunit.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/uaspkpl:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/uaspkpl:${{ github.sha }}
